version: "3.9"

services:
  web:
    build: .
    working_dir: /code/bookstore
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstoreuser
      POSTGRES_PASSWORD: bookstorepass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
